name: 'Twingate GitHub Action'
description: 'Connect to Twingate network in GitHub Actions'
author: 'maherapi'
inputs:
  service-key:
    description: 'Twingate Service Key'
    required: true
  auto-cleanup:
    description: 'Automatically cleanup Twingate connection after workflow completes'
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/cleanup.js'
  post-if: 'always()'
